### ISSUE TITLE
录屏无法使用

### ISSUE THREAD

**Issue by Kevin-liutianping** [yanchunhuo/AutomationTest#13]
您好，为什么Appium的录屏无法使用
``` python
driver.start_recording_screen(forcedRestart=True)
----------------------此处步骤省略
driver.stop_recording_screen()
```
Appium日志如下
![image](https://user-images.githubusercontent.com/40854706/134810816-965917fd-0f29-4786-9cfb-cd7c5b8d2c6b.png)

**Comment by yanchunhuo** [comment]
@Kevin-liutianping 需要确保手机系统有权限录屏，可以先用adb进行push、pull对应目录，确保有目录的读写权限。大部分手机厂商会做限制
